site_name: "3d_exp Filament settings"
dev_addr: '0.0.0.0:8000'

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences

theme:
  name: material

nav:
  - Home: index.md
  - Links: information.md
  
